### ISSUE TITLE
HLS Support: Allow smaller alignments than 64 bytes

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/snap#165]
Currently we need to align writeable data to at least 64 bytes, since the AXI bus used as interface for action_wrapper is 512 bit wide. This imposes problems once 8 byte or even less should be written in host-memory where there might be important data (e.g. malloc stuff) before or after the buffer-address used. Whereas internally there are byte-enables possible for the PSL accessed memory, HLS currently has no means to deal with that.

**Comment by jsvogt** [comment]
SNAP supports byte-enables on AXI. 
No HLS support for byte-enables, or don't know how to code in HLS.
Consider together with CAPI 2.0 DMA changes.

**Comment by luyong6** [comment]
Are we going to provide some functions to allow user access smaller alignment for the data array? Current fixed 64bytes membus_t always makes me crazy for the data casting...
Currently I either to "ASSUME" that data format is 64bytes aligned, which may not be true in real applications, or do some complex packing and unpacking, which is a headache.

**Comment by fhaverkamp** [comment]
@luyong6 I fully agree, but I do not see how a fix is supposed to look like. The width of the AXI bus seems to be given and from an HLS perspective there is no way to set byte enables as an HDL based action might be able to do. The only thing in HLS which might allow that is using the build in memcpy(), but I think that is not a golden solution either, since it has so much trouble with castings. Do you have any idea how such a thing could be fixed?

**Comment by luyong6** [comment]
In my recent practice of a "customer" hash-join, I experimented some ideas like following:

- let S = sizeof(element_t), how many *bytes* does element_t have
- let N = number of elements wanted
- let M = number of elements in one batch of memory access

In theory, element_t can be any number of bits. Here we define it in bytes. 
And assume there is an equation of 
```
S * 8bits * M = 512bits * BL
```

Here 512 is the AXI bus width (in bits), and `BL` is AXI burst length which follows the limitation of AXI spec. For example, when element_t is `long`: S = 8, and M can be 8/16/24/.... while BL=1/2/3/....

```C
//BPERDW = 512b/8b = 64
int imodM = 0;
snap_membus_t tempdata[BL];
element_t     element_table[N];
element_t     element_current;


int left_bytes = N * sizeof(element_t);
for (i = 0; i < N; i++) {

    //memory read
    if (imodM == 0) {
        addr = start_addr + BL * BPERDW; //byte address
        xfer_bytes = min(BL * BPERDW, left_bytes);
        memcpy(din_gmem + addr, tempdata, xfer_bytes);
        left_bytes -= xfer_bytes;
    }

    //This pseudo code is the most ugly part!
    //And it may requires conjunction of more than one tempdata
    element_current = tempdata[?](bitrange_hi, bitrange_lo); 
    
    element_table[i] = element_current;
    //some small processing just to the current element can be added here.

    //Use imodM but not using i%M is trying to avoid a division.
    //imonM is just a counter counting from 0...M-1
    imodM ++;
    if(imodM == M)
        imodM = 0;
}

//You get the entire element_table now. Then do calculations as you want.
//......
function_on_element_table();

```

The problem is: 
- the pseudo code for bit range extraction is very ugly. I don't have any better ideas.
- HLS didn't make the for-loop and function_on_element_table pipelined. Maybe I still didn't catch the meaning of `HLS DATAFLOW` pragma. They are executed in serial now.

**Comment by jsvogt** [comment]
No plan to fix this. For CAPI 2.0, we currently support 128 byte writes only. Revisit when CAPI 2.0 DMA byte alignment is on the table again.
