### ISSUE TITLE
PR flow: Documentation required

### ISSUE THREAD

**Issue by boekholt** [open-power/snap#411]
We need to describe the PR flow for the cloud.

**Comment by bmesnet** [comment]
PR Flow is used for the CAPI1.0. cloud only. From the PSL DCP downloaded from the webiste, we were building as much DCP that the card was requiring drivers (ADKU3 board had 1 DCP with just PSL and 1 DCP with PSL + DDR driver - N250S had 1 DCP with PSL only, 1 DCP with PSL + DDR driver and 1 DCP with PSL + DDR driver + NVME driver). The cloud option was so merging user design with the right DCP depending on his configuration. The main reason of this PR flow for CAPI1.0 was the complexity to time the design with this PSL DCP.
For CAPI2.0, PR will not be implement since an encrypted PSL is provided as a zip file and will be used as for any image build. There is no specific timing issue with CAPI2.0 since the PSL/BSP is not contained in a fixed location. The cloud option will be kept to almost to generate the MD5 signature needed for all image built in Nimbix.
For OpenCAPI implementation in the cloud, we may use PR again.

For this reason, the focus is not to document an option on an old technology that may not be kept when Power9 will replace Power8 on cloud => closing this issue
