### ISSUE TITLE
hdl_helloworld enhancements

### ISSUE THREAD

**Issue by bmesnet** [open-power/snap#820]
May be few enhacements:

    Shouldn't we add DISABLE_SDRAM_AND_BRAM and DISABLE_NVME in Kconfig to be sure not to enable them by error?
    can the application filename begin as all other application filename by snap_xxx?

hardware/Makefilesays to print all messages produced by

    @$(MAKE) -C $(ACTION_ROOT) hw

into action_make.log:

snap/hardware/Makefile

Line 242 in b6254c4
 @$(MAKE) -C $(ACTION_ROOT) hw >> $(LOGS_DIR)/action_make.log; 

All other messages of the make process are visible on the console. Therefore, when testing this branch I was surprised to see no messages for the creation of any action user IP.
So, maybe that should be changed.

**Comment by acastellane** [comment]
Creating new branch HDL_helloworld_updates for these.

**Comment by boekholt** [comment]
Fixed with #822.
Changing this was already part of pull request #819. After a rebase of  the corresponding branch I closed #819 and opened #822 which still contains that change.
@acastellane The remote version of HDL_helloworld_updates does not yet contain the change. So, it looks like it is only existing in your local version. You may remove that change (for instace via `git checkout HDL_helloworld_updates; git rebase --interactive master`).

**Comment by bmesnet** [comment]
Seems ok to close. Thanks
